source 'https://rubygems.org'

gem 'rails', '3.2.13'


gem 'sqlite3'
gem 'backbone-rails'
gem 'ejs'
gem 'underscore-rails'
gem 'pry-rails'
gem 'better_errors'
gem 'binding_of_caller'

group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer', :platforms => :ruby

  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'
